event_started = "This event has already started."
rsvp_deadline_passed = "The RSVP deadline for this event has passed. You may be able to attend/alter your RSVP, but please check with the host first."
already_rsvpd = "You have already RSVP'd to this event."
no_rsvps_added = "No new RSVPs added (they may already be attending)"
regular_ping = "{title} RSVP is up!\n{regulars_str}\n\nTalk to an event host if you want to be added to this list for future events!"
event_footer = "To RSVP for multiple people or remove your RSVP, click the RSVP button a second time!"
personal_rsvp = ":heavy_plus_sign: RSVP for a personal guest"
slack_rsvp = ":slack: RSVP for Slack users"
remove_rsvp = "Remove RSVP"
rsvp_slack_warning = "People you RSVP for here will be the *only ones able to remove their RSVP* except for event hosts. You will not be able to remove it for them."
user_select = "Select users to RSVP for"
admin_tools = "Event hosts can make changes to this event here"
rsvp_removed = "Your RSVP has been removed. You can change your mind until <!date^{timestamp}^{{time}} {{date_long_pretty}}|{time_formatted}>."
rsvp_added = "Your guest has been added to the RSVP list. *Including yourself* you have RSVP'd for {rsvp_count} people."
rsvp_slack_added = (
    "The following {user_plural} been added to the RSVP list:\n{user_list}"
)
rsvp_slack_not_added = "The following {user_plural} already attending:\n{user_list}"
not_host = "You are not listed as a host for this event. Please contact the event host if you need to make changes."
host_can_edit = "Hosts you add here will be able to edit the event (including removing you as a host)"
edit_rsvp_options = "Renaming an option *will not remove* the users who have already RSVP'd to it. Use this function responsibly."
app_home_title = "Event RSVPs"
app_home_description = (
    "You can use this space to create events and (one day) manage your RSVPs!"
)
create_event = "Create your event! An event with an engaging description and a striking image has a better chance of attracting attendees.\n\nYou'll be able to edit it later and add RSVP options and guests as desired."
