event_started = "This event has already started."
rsvp_deadline_passed = "The RSVP deadline for this event has passed. You may be able to attend/alter your RSVP, but please check with the host first."
already_rsvpd = "You have already RSVP'd to this event."
no_rsvps_added = "No new RSVPs added (they may already be attending)"
regular_ping = "{title} RSVP is up!\n{regulars_str}\n\nTalk to an event host if you want to be added to this list for future events!"
event_footer = "To RSVP for multiple people or remove your RSVP, click the RSVP button a second time!"
personal_rsvp = ":heavy_plus_sign: RSVP for a personal guest"
slack_rsvp = ":slack: RSVP for Slack users"
remove_rsvp = "Remove RSVP"
rsvp_slack_warning = "People you RSVP for here will be the *only ones able to remove their RSVP*. You will not be able to remove it for them."
user_select = "Select users to RSVP for"
admin_tools = "Event hosts can make changes to this event here"
rsvp_removed = "Your RSVP has been removed. You can change your mind until <!date^{timestamp}^{{time}} {{date_long_pretty}}|{time_formatted}>."
rsvp_added = "Your guest has been added to the RSVP list. *Including yourself* you have RSVP'd for {rsvp_count} people."
rsvp_slack_added = (
    "The following {user_plural} been added to the RSVP list:\n{user_list}"
)
rsvp_slack_not_added = "The following {user_plural} already attending:\n{user_list}"
